'use strict';

const FEATURE_CATALOG = [
  {
    key: 'tag_name',
    title: 'Root Tag Name',
    family: 'structure',
    level: 'list',
    type: 'categorical',
    keywordFeature: false,
    description: 'The HTML tag used by the candidate root, such as div, section, article, ul, or ol.',
    meaning: 'This tells the model what kind of container the candidate is trying to be.',
  },
  {
    key: 'role_attribute',
    title: 'Role Attribute',
    family: 'structure',
    level: 'list',
    type: 'categorical',
    keywordFeature: false,
    description: 'The root element role value when present.',
    meaning: 'Roles such as feed or comment can be strong non-visual hints.',
  },
  {
    key: 'classes_count',
    title: 'Class Count',
    family: 'structure',
    level: 'list',
    type: 'number',
    keywordFeature: false,
    description: 'How many CSS classes exist on the candidate root.',
    meaning: 'This is a coarse summary of root complexity without memorizing exact class strings.',
  },
  {
    key: 'data_attributes_count',
    title: 'Data Attribute Count',
    family: 'structure',
    level: 'list',
    type: 'number',
    keywordFeature: false,
    description: 'How many data-* attributes appear on the candidate root.',
    meaning: 'Large app widgets and framework containers often expose useful machine-readable markers here.',
  },
  {
    key: 'aria_attributes_count',
    title: 'ARIA Attribute Count',
    family: 'structure',
    level: 'list',
    type: 'number',
    keywordFeature: false,
    description: 'How many aria-* attributes exist on the candidate root.',
    meaning: 'Accessibility-heavy discussion widgets often surface semantics through ARIA metadata.',
  },
  {
    key: 'node_depth',
    title: 'Node Depth',
    family: 'structure',
    level: 'list',
    type: 'number',
    keywordFeature: false,
    description: 'The DOM depth of the candidate root.',
    meaning: 'Comment lists often appear deeper than headers and nav bars, but not as deep as tiny leaf nodes.',
  },
  {
    key: 'child_tag_variety',
    title: 'Child Tag Variety',
    family: 'structure',
    level: 'list',
    type: 'number',
    keywordFeature: false,
    description: 'How many distinct direct-child tags exist under the candidate.',
    meaning: 'This estimates how structurally diverse the root is.',
  },
  {
    key: 'direct_child_count',
    title: 'Direct Child Count',
    family: 'structure',
    level: 'list',
    type: 'number',
    keywordFeature: false,
    description: 'The number of direct child elements beneath the candidate root.',
    meaning: 'Comment lists usually have multiple direct children or repeated wrappers.',
  },
  {
    key: 'repeating_group_count',
    title: 'Repeating Group Count',
    family: 'repeated_blocks',
    level: 'block',
    type: 'number',
    keywordFeature: false,
    description: 'How many dominant repeated child units were detected under the candidate.',
    meaning: 'This is one of the strongest signs that a candidate is a comment list rather than a singleton box.',
  },
  {
    key: 'child_sig_id_group_count',
    title: 'Child Signature Group Count',
    family: 'repeated_blocks',
    level: 'block',
    type: 'number',
    keywordFeature: false,
    description: 'How many direct-child structural signature groups exist.',
    meaning: 'This helps estimate whether the root has a coherent repeated family or a messy mixed layout.',
  },
  {
    key: 'child_xpath_star_group_count',
    title: 'Child XPath-Star Group Count',
    family: 'repeated_blocks',
    level: 'block',
    type: 'number',
    keywordFeature: false,
    description: 'How many repeated child families appear under wildcard XPath grouping.',
    meaning: 'This captures repeated sibling structure using locator-style grouping.',
  },
  {
    key: 'xpath_star_group_count',
    title: 'XPath-Star Group Size',
    family: 'repeated_blocks',
    level: 'block',
    type: 'number',
    keywordFeature: false,
    description: 'The size of the strongest wildcard-XPath repeated family.',
    meaning: 'This approximates how many comment blocks may exist in the list.',
  },
  {
    key: 'min_k_threshold_pass_3',
    title: 'Min-K Pass 3',
    family: 'repeated_blocks',
    level: 'block',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether the repeated-unit family has at least 3 units.',
    meaning: 'A short but meaningful repeated discussion/review list often starts becoming visible here.',
  },
  {
    key: 'min_k_threshold_pass_5',
    title: 'Min-K Pass 5',
    family: 'repeated_blocks',
    level: 'block',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether the repeated-unit family has at least 5 units.',
    meaning: 'Larger repeated lists are often more trustworthy than tiny repeated structures.',
  },
  {
    key: 'min_k_threshold_pass_8',
    title: 'Min-K Pass 8',
    family: 'repeated_blocks',
    level: 'block',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether the repeated-unit family has at least 8 units.',
    meaning: 'This is a stronger signal of a meaningful repeated discussion feed.',
  },
  {
    key: 'min_k_threshold_pass_15',
    title: 'Min-K Pass 15',
    family: 'repeated_blocks',
    level: 'block',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether the repeated-unit family has at least 15 units.',
    meaning: 'Very large repeated structures can strongly indicate comment/review feeds, though some product grids also qualify.',
  },
  {
    key: 'sig_id_count_weak',
    title: 'Weak Signature Repetition',
    family: 'repeated_blocks',
    level: 'block',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether the repeated-unit signature passes the weak repetition threshold.',
    meaning: 'A weak pass means there is some repeated structure, but it may still be noisy.',
  },
  {
    key: 'sig_id_count_medium',
    title: 'Medium Signature Repetition',
    family: 'repeated_blocks',
    level: 'block',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether the repeated-unit signature passes the medium repetition threshold.',
    meaning: 'Medium repetition is a better sign of stable comment-block structure.',
  },
  {
    key: 'sig_id_count_strong',
    title: 'Strong Signature Repetition',
    family: 'repeated_blocks',
    level: 'block',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether the repeated-unit signature passes the strong repetition threshold.',
    meaning: 'Strong repetition often means the candidate is built from many similarly structured blocks.',
  },
  {
    key: 'sibling_homogeneity_score',
    title: 'Sibling Homogeneity Score',
    family: 'repeated_blocks',
    level: 'block',
    type: 'number',
    keywordFeature: false,
    description: 'How uniform the repeated sibling units are.',
    meaning: 'Real comment lists usually have blocks that look more alike than generic mixed-content regions.',
  },
  {
    key: 'sig_id_recursive_nesting',
    title: 'Recursive Nesting',
    family: 'repeated_blocks',
    level: 'block',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether repeated structure appears recursively inside repeated structure.',
    meaning: 'This is useful for thread and reply nesting patterns.',
  },
  {
    key: 'reply_nesting_depth',
    title: 'Reply Nesting Depth',
    family: 'repeated_blocks',
    level: 'block',
    type: 'number',
    keywordFeature: false,
    description: 'Estimated nesting depth of reply-like structure under the candidate.',
    meaning: 'Threaded comment systems often show this more clearly than flat product grids.',
  },
  {
    key: 'text_word_count',
    title: 'Text Word Count',
    family: 'text_body',
    level: 'element',
    type: 'number',
    keywordFeature: false,
    description: 'Approximate number of words inside the candidate subtree.',
    meaning: 'Real discussion/review regions usually carry a non-trivial amount of user-authored text.',
  },
  {
    key: 'text_char_count',
    title: 'Text Character Count',
    family: 'text_body',
    level: 'element',
    type: 'number',
    keywordFeature: false,
    description: 'Approximate number of text characters inside the candidate subtree.',
    meaning: 'This helps separate text-heavy user content from sparse control regions.',
  },
  {
    key: 'text_sentence_count',
    title: 'Text Sentence Count',
    family: 'text_body',
    level: 'element',
    type: 'number',
    keywordFeature: false,
    description: 'Estimated count of sentence-like spans in the candidate subtree.',
    meaning: 'Comment lists often include multiple sentence-like bodies across blocks.',
  },
  {
    key: 'has_text_content',
    title: 'Has Text Content',
    family: 'text_body',
    level: 'element',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether the candidate appears to contain meaningful text content.',
    meaning: 'This guards against purely structural but text-poor false positives.',
  },
  {
    key: 'text_contains_links',
    title: 'Contains Links',
    family: 'text_body',
    level: 'element',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether text-bearing nodes also contain links.',
    meaning: 'Some discussion systems include profile and permalink links, but link-heavy navigation regions can also trigger this.',
  },
  {
    key: 'link_density',
    title: 'Link Density',
    family: 'text_body',
    level: 'element',
    type: 'number',
    keywordFeature: false,
    description: 'How link-heavy the candidate text is.',
    meaning: 'Very high link density often suggests navigation or directory pages rather than comments.',
  },
  {
    key: 'no_text_content_in_units',
    title: 'No Text In Units',
    family: 'text_body',
    level: 'block',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether repeated units exist but contain little meaningful text.',
    meaning: 'This is a negative sign for real user-authored discussion blocks.',
  },
  {
    key: 'comment_header_with_count',
    title: 'Comment Header With Count',
    family: 'lexical_keywords',
    level: 'list',
    type: 'boolean',
    keywordFeature: true,
    description: 'Whether a nearby header resembles text like "34 comments" or similar.',
    meaning: 'This is an explicit lexical clue that the region may be a comment list.',
  },
  {
    key: 'attributes_contain_keywords',
    title: 'Attributes Contain Keywords',
    family: 'lexical_keywords',
    level: 'list',
    type: 'boolean',
    keywordFeature: true,
    description: 'Whether attribute names, values, tag names, or short direct text contain comment-like keywords.',
    meaning: 'This captures explicit lexical naming of the region.',
  },
  {
    key: 'keyword_container_high',
    title: 'High-Confidence Container Keywords',
    family: 'lexical_keywords',
    level: 'list',
    type: 'boolean',
    keywordFeature: true,
    description: 'Whether strong keywords like comment, review, reply, or forum appear at the container level.',
    meaning: 'This is a direct lexical hint from the candidate wrapper itself.',
  },
  {
    key: 'keyword_text_high',
    title: 'High-Confidence Text Keywords',
    family: 'lexical_keywords',
    level: 'element',
    type: 'boolean',
    keywordFeature: true,
    description: 'Whether strong comment-like keywords appear in visible text.',
    meaning: 'This can help on easy pages, but may overfit if overused.',
  },
  {
    key: 'keyword_text_med',
    title: 'Medium-Confidence Text Keywords',
    family: 'lexical_keywords',
    level: 'element',
    type: 'boolean',
    keywordFeature: true,
    description: 'Whether medium-confidence discussion terms like post or message appear in visible text.',
    meaning: 'These are weaker lexical hints than direct comment/review keywords.',
  },
  {
    key: 'keyword_direct_text_high',
    title: 'High-Confidence Direct Text Keywords',
    family: 'lexical_keywords',
    level: 'element',
    type: 'boolean',
    keywordFeature: true,
    description: 'Whether strong keywords appear in short direct text close to the candidate root.',
    meaning: 'This can highlight local labels like Comments or Replies without relying on full subtree text.',
  },
  {
    key: 'keyword_attr_name_high',
    title: 'High-Confidence Attribute Name Keywords',
    family: 'lexical_keywords',
    level: 'list',
    type: 'boolean',
    keywordFeature: true,
    description: 'Whether strong keywords appear specifically in attribute names.',
    meaning: 'Custom widgets often hide useful naming inside data-* or aria-* attribute names.',
  },
  {
    key: 'keyword_attr_value_high',
    title: 'High-Confidence Attribute Value Keywords',
    family: 'lexical_keywords',
    level: 'list',
    type: 'boolean',
    keywordFeature: true,
    description: 'Whether strong keywords appear specifically in attribute values.',
    meaning: 'This catches app-level or CSS-level naming patterns without using full raw text.',
  },
  {
    key: 'keyword_unit_high_coverage',
    title: 'Keyword Unit Coverage',
    family: 'lexical_keywords',
    level: 'block',
    type: 'number',
    keywordFeature: true,
    description: 'Fraction of repeated units that carry strong comment-like keywords.',
    meaning: 'Broad keyword coverage across units is stronger than a single isolated keyword.',
  },
  {
    key: 'submit_button_keyword_high',
    title: 'High-Confidence Submit Keywords',
    family: 'lexical_keywords',
    level: 'context',
    type: 'boolean',
    keywordFeature: true,
    description: 'Whether nearby submit controls carry strong comment or reply wording.',
    meaning: 'This helps identify discussion composers, but can also bias the model toward lexical shortcuts.',
  },
  {
    key: 'schema_org_comment_itemtype',
    title: 'Schema.org Comment Type',
    family: 'semantic_markup',
    level: 'list',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether schema.org Comment or Review markup is present.',
    meaning: 'This is explicit semantic markup, but not just plain lexical text.',
  },
  {
    key: 'aria_role_comment',
    title: 'ARIA Role Comment',
    family: 'semantic_markup',
    level: 'list',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether the candidate or nearby structure exposes a comment-related ARIA role.',
    meaning: 'This is accessibility semantics rather than visible wording.',
  },
  {
    key: 'aria_role_feed_with_articles',
    title: 'ARIA Feed With Articles',
    family: 'semantic_markup',
    level: 'list',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether the candidate looks like a feed/article structure in ARIA terms.',
    meaning: 'Some discussion systems expose this feed-like semantic layout.',
  },
  {
    key: 'microdata_itemprop_author',
    title: 'Microdata Author',
    family: 'semantic_markup',
    level: 'block',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether microdata author fields appear inside the candidate.',
    meaning: 'Comment and review blocks often annotate authors explicitly.',
  },
  {
    key: 'microdata_itemprop_date_published',
    title: 'Microdata Date Published',
    family: 'semantic_markup',
    level: 'block',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether microdata date-published fields appear inside the candidate.',
    meaning: 'This supports the idea that repeated units are authored timestamped content blocks.',
  },
  {
    key: 'microdata_itemprop_text',
    title: 'Microdata Text',
    family: 'semantic_markup',
    level: 'element',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether microdata text fields appear inside the candidate.',
    meaning: 'This points more directly at user-authored message content.',
  },
  {
    key: 'json_ld_has_comment_type',
    title: 'JSON-LD Comment Type',
    family: 'semantic_markup',
    level: 'list',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether JSON-LD markup references comment-like objects.',
    meaning: 'This is another structured semantic hint that avoids raw-text dependence.',
  },
  {
    key: 'json_ld_has_comment_action',
    title: 'JSON-LD Comment Action',
    family: 'semantic_markup',
    level: 'context',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether JSON-LD markup references comment or interaction actions.',
    meaning: 'This can support the presence of a discussion or response system.',
  },
  {
    key: 'includes_author',
    title: 'Includes Author',
    family: 'author_time_identity',
    level: 'block',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether author-like identity markers appear in the candidate.',
    meaning: 'User-authored blocks usually show who wrote the content.',
  },
  {
    key: 'has_avatar',
    title: 'Has Avatar',
    family: 'author_time_identity',
    level: 'block',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether avatar or profile-image signals appear in the candidate.',
    meaning: 'Many discussion systems visually pair user text with avatars.',
  },
  {
    key: 'author_avatar_coverage',
    title: 'Author+Avatar Coverage',
    family: 'author_time_identity',
    level: 'block',
    type: 'number',
    keywordFeature: false,
    description: 'Fraction of repeated units that show author-plus-avatar style evidence.',
    meaning: 'Coverage across blocks is more informative than a one-off avatar.',
  },
  {
    key: 'profile_link_coverage',
    title: 'Profile Link Coverage',
    family: 'author_time_identity',
    level: 'block',
    type: 'number',
    keywordFeature: false,
    description: 'Fraction of repeated units with profile-link style evidence.',
    meaning: 'Discussion blocks often link usernames or profiles consistently.',
  },
  {
    key: 'author_timestamp_colocated',
    title: 'Author+Timestamp Colocated',
    family: 'author_time_identity',
    level: 'block',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether author and timestamp signals appear together inside units.',
    meaning: 'This is one of the stronger signatures of real comment or review blocks.',
  },
  {
    key: 'time_datetime_per_unit',
    title: 'Datetime Coverage',
    family: 'author_time_identity',
    level: 'block',
    type: 'number',
    keywordFeature: false,
    description: 'Fraction of repeated units that expose datetime-style evidence.',
    meaning: 'Timestamp coverage across blocks is a strong authored-content signal.',
  },
  {
    key: 'has_relative_time',
    title: 'Has Relative Time',
    family: 'author_time_identity',
    level: 'block',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether relative-time patterns such as 5m, 2d, or yesterday appear.',
    meaning: 'This often appears in user-generated conversation and review systems.',
  },
  {
    key: 'reply_button_unit_coverage',
    title: 'Reply Button Coverage',
    family: 'interaction_controls',
    level: 'block',
    type: 'number',
    keywordFeature: false,
    description: 'Fraction of repeated units that show reply-like controls.',
    meaning: 'True discussion blocks often expose reply actions repeatedly.',
  },
  {
    key: 'reaction_coverage',
    title: 'Reaction Coverage',
    family: 'interaction_controls',
    level: 'block',
    type: 'number',
    keywordFeature: false,
    description: 'Fraction of repeated units that show reaction or like-style indicators.',
    meaning: 'This can help distinguish real social/discussion blocks from plain lists.',
  },
  {
    key: 'edit_delete_coverage',
    title: 'Edit/Delete Coverage',
    family: 'interaction_controls',
    level: 'block',
    type: 'number',
    keywordFeature: false,
    description: 'Fraction of repeated units that show edit, delete, or moderation controls.',
    meaning: 'Discussion systems often expose these controls consistently across blocks.',
  },
  {
    key: 'has_nearby_textarea',
    title: 'Has Nearby Textarea',
    family: 'interaction_controls',
    level: 'context',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether the candidate sits near a textarea-style composer.',
    meaning: 'Comment lists often live near a reply or submission composer.',
  },
  {
    key: 'aligned_with_textarea',
    title: 'Aligned With Textarea',
    family: 'interaction_controls',
    level: 'context',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether the candidate appears structurally aligned with a nearby textarea.',
    meaning: 'This helps connect discussion lists to their composers.',
  },
  {
    key: 'aligned_with_content_editable',
    title: 'Aligned With ContentEditable',
    family: 'interaction_controls',
    level: 'context',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether the candidate aligns with a contenteditable composer area.',
    meaning: 'Some apps use rich editors instead of plain textareas.',
  },
  {
    key: 'submit_button_present',
    title: 'Submit Button Present',
    family: 'interaction_controls',
    level: 'context',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether a nearby submit-style control exists at all.',
    meaning: 'Presence of a composer plus submit control can support a discussion interpretation.',
  },
  {
    key: 'collapse_expand_control',
    title: 'Collapse/Expand Control',
    family: 'interaction_controls',
    level: 'block',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether show-more or collapse/expand style controls appear inside the candidate.',
    meaning: 'Long threads and review lists often expose expansion controls.',
  },
  {
    key: 'pagination_load_more_adjacent',
    title: 'Load-More Adjacent',
    family: 'interaction_controls',
    level: 'list',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether pagination or load-more controls appear near the candidate.',
    meaning: 'Discussion feeds often paginate or lazy-load more units.',
  },
  {
    key: 'table_row_structure',
    title: 'Table Row Structure',
    family: 'negative_controls',
    level: 'list',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether the candidate looks like tabular row data rather than user discussion blocks.',
    meaning: 'This is a strong false-positive suppression feature.',
  },
  {
    key: 'add_to_cart_present',
    title: 'Add-To-Cart Present',
    family: 'negative_controls',
    level: 'list',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether commerce call-to-action signals appear in the candidate.',
    meaning: 'This helps reject product grids and listing cards.',
  },
  {
    key: 'nav_header_ancestor',
    title: 'Nav/Header Ancestor',
    family: 'negative_controls',
    level: 'list',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether the candidate sits inside navigation or header-like ancestry.',
    meaning: 'This suppresses menus and top-page furniture.',
  },
  {
    key: 'high_external_link_density',
    title: 'High External Link Density',
    family: 'negative_controls',
    level: 'list',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether the candidate is heavily dominated by external links.',
    meaning: 'Directory-style or recommendation regions often look like this.',
  },
  {
    key: 'external_link_density_low',
    title: 'Low External Link Density',
    family: 'negative_controls',
    level: 'list',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether external link density remains low.',
    meaning: 'This can support comment-list interpretation when paired with real text.',
  },
  {
    key: 'star_rating_no_text',
    title: 'Star Rating Without Text',
    family: 'negative_controls',
    level: 'block',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether rating-style stars exist without meaningful review text.',
    meaning: 'This helps reject rating widgets that are not real review bodies.',
  },
  {
    key: 'price_currency_in_unit',
    title: 'Price/Currency In Unit',
    family: 'negative_controls',
    level: 'block',
    type: 'boolean',
    keywordFeature: false,
    description: 'Whether repeated units contain price or currency patterns.',
    meaning: 'This helps distinguish commerce cards from comments and replies.',
  },
  {
    key: 'frame_count',
    title: 'Frame Count',
    family: 'context',
    level: 'context',
    type: 'number',
    keywordFeature: false,
    description: 'How many frames were visible when the page or snapshot was analyzed.',
    meaning: 'Frame-heavy pages can be harder to interpret and may affect reliability.',
  },
  {
    key: 'analysis_source',
    title: 'Analysis Source',
    family: 'context',
    level: 'context',
    type: 'categorical',
    keywordFeature: false,
    description: 'Whether the row came from automated scanning or a manual snapshot.',
    meaning: 'Manual-snapshot rows often represent harder cases and may behave differently.',
  },
  {
    key: 'blocker_type',
    title: 'Blocker Type',
    family: 'context',
    level: 'context',
    type: 'categorical',
    keywordFeature: false,
    description: 'Whether the page showed a blocker such as login wall or captcha.',
    meaning: 'This can explain difficult or degraded candidates without turning the blocker into the main signal.',
  },
];

function getFeatureCatalog() {
  return FEATURE_CATALOG.map((entry) => ({ ...entry }));
}

const FEATURE_FAMILIES = [
  {
    key: 'structure',
    title: 'Structure',
    description: 'Root-level container shape, depth, and basic DOM identity.',
  },
  {
    key: 'repeated_blocks',
    title: 'Repeated Blocks',
    description: 'Evidence that the candidate contains a repeated family of comment blocks.',
  },
  {
    key: 'text_body',
    title: 'Text Body',
    description: 'How much real text exists and whether the repeated units look text-bearing.',
  },
  {
    key: 'lexical_keywords',
    title: 'Lexical Keywords',
    description: 'Direct keyword evidence such as comment, review, reply, or forum-style wording.',
  },
  {
    key: 'semantic_markup',
    title: 'Semantic Markup',
    description: 'Schema.org, ARIA, and microdata hints that describe the page semantically.',
  },
  {
    key: 'author_time_identity',
    title: 'Author, Time, Identity',
    description: 'Signals that repeated units look like authored user content with identity and time markers.',
  },
  {
    key: 'interaction_controls',
    title: 'Interaction Controls',
    description: 'Reply, composer, load-more, and moderation-style controls around the list.',
  },
  {
    key: 'negative_controls',
    title: 'Negative Controls',
    description: 'Signals that help reject product grids, nav regions, and other structured false positives.',
  },
  {
    key: 'context',
    title: 'Context',
    description: 'Environment-level information such as source mode and blocker state.',
  },
];

function getFeatureCatalogForVariant(variant) {
  const excludeKeywordFeatures = !!(variant && variant.excludeKeywordFeatures);
  return FEATURE_CATALOG
    .filter((entry) => !excludeKeywordFeatures || !entry.keywordFeature)
    .map((entry) => ({ ...entry }));
}

function buildFeatureEntryIndex(catalog = FEATURE_CATALOG) {
  return new Map((catalog || []).map((entry) => [entry.key, { ...entry }]));
}

function groupFeaturesByFamily(catalog = FEATURE_CATALOG) {
  const features = Array.isArray(catalog) ? catalog : FEATURE_CATALOG;
  const grouped = FEATURE_FAMILIES.map((family) => ({
    ...family,
    features: [],
  }));
  const familyIndex = new Map(grouped.map((family) => [family.key, family]));

  features.forEach((entry) => {
    const family = familyIndex.get(entry.family);
    if (!family) return;
    family.features.push({ ...entry });
  });

  return grouped;
}

module.exports = {
  FEATURE_CATALOG,
  FEATURE_FAMILIES,
  getFeatureCatalog,
  getFeatureCatalogForVariant,
  buildFeatureEntryIndex,
  groupFeaturesByFamily,
};
